jaffle_shop:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/home/cyril/Documents/vscode_project/dbt_project/jaffle_shop-main/jaffle_shop.duckdb'
      extensions:
        - httpfs
        - parquet